Update Apps to newest Version 01.07.23

diff --git a/apps/reboot b/apps/reboot
--- a/apps/reboot
+++ b/apps/reboot
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-revision="reboot Unit v0.1.2 (2021-02-25 by MIBonk)"
+revision="reboot Unit v0.1.5 (2023-06-28 by MIBonk)"
 # use --help for more info
 
 export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
@@ -12,55 +12,55 @@ thisdir="$(dirname $0)"
 
 if [ -z $LOG ]; then
 	. $thisdir/../config/GLOBALS
-	echo -ne "\n$ME-$thisname---->\n" >> $LOG
 fi
 
+echo -ne "\n$ME-$thisname---->\n" >> $LOG
+
 if [ -f $TMP/flash.mib ] || [ -f $TMP/backup.mib ] || [ -f $TMP/rccd.mib ] || [ -f $TMP/svm.mib ] || [ -f /$TMP/vim.mib ] || [ -f $TMP/ambient.mib ]; then
-	echo "Some other process is already running... reboot not possible!"
+	echo "Reboot not possible because some other process is already running!" | $TEE -a $LOG
 	return 2> /dev/null
 fi
 
-	case $1 in
-
+case $1 in
 	-t) {
+		touch $TMP/reboot.mib
 
-touch $TMP/reboot.mib
+		REBOOT="reboot"
+		if [[ $3 = "fast" ]]; then
+			REBOOT="fastReboot"
+		fi
 
-REBOOT="reboot"
-if [[ $3 = "fast" ]]; then
-	REBOOT="fastReboot"
-fi
+		sync; sync; sync
+		#trap 2
 
-sync; sync; sync
-#trap 2
+		trap ctrl_c INT
 
-trap ctrl_c INT
+		function ctrl_c {
+			rm -rf $TMP/reboot.mib
+			exit 0
+		}
 
-function ctrl_c {
-	rm -rf $TMP/reboot.mib
-	exit 0
-}
-
-[ -z "$GEM" ] && echo -ne "\033[31m"
-echo -ne "Reboot Unit..." | $TEE -a $LOG
-[ -n "$GEM" ] && echo -ne "\n" | $TEE -a $LOG
-[ -z "$GEM" ] && echo -ne " press CTRL-C to abort!!!\n" | $TEE -a $LOG
-[ -z "$GEM" ] && echo -ne "\n\033[00;00m"
-[ -z "$GEM" ] && echo -ne "$2 seconds left..."
-[ -n "$GEM" ] && echo -ne "Unit is Rebooting now...\n"
-let COUNTER=$2-1
-	while [ $COUNTER -gt -1 ]; do
-		sleep 1
-		[ -z "$GEM" ] &&echo -ne "$COUNTER..."
-		let COUNTER=COUNTER-1
-	done
-[ -z "$GEM" ] && echo -ne "\n\n"
-[ -z "$GEM" ] && echo -ne "Unit is Rebooting now...\n" | $TEE -a $LOG
-[ -z "$GEM" ] && echo -ne "\n"
-on -f rcc /usr/apps/mib2_ioc_flash $REBOOT 2>>$LOG
-
-return 2> /dev/null
-
+		echo -ne "Reboot Unit..." | $TEE -a $LOG
+		[ -z "$GEM" ] && echo -ne "\033[31m"
+		[ -n "$GEM" ] && echo -ne "\n" | $TEE -a $LOG
+		[ -z "$GEM" ] && echo -ne " press CTRL-C to abort!!!\n" | $TEE -a $LOG
+		[ -z "$GEM" ] && echo -ne "\n\033[00;00m"
+		[ -z "$GEM" ] && echo -ne "$2 seconds left..."
+		[ -n "$GEM" ] && echo -ne "Unit is rebooting now...\n" | $TEE -a $LOG
+		let COUNTER=$2-1
+			while [ $COUNTER -gt -1 ]; do
+				sleep 1
+				[ -z "$GEM" ] &&echo -ne "$COUNTER..."
+				let COUNTER=COUNTER-1
+			done
+		[ -z "$GEM" ] && echo -ne "\nUnit is rebooting now...\n" | $TEE -a $LOG
+		if [[ "$TRAINVERSION" = *MHIG* ]]; then
+			echo -ne "\nButtons will stop working now\nScreen might turn off\nReboot will take ~60s\n" | $TEE -a $LOG
+			on -f mmx slay -f j9
+		else
+			on -f rcc /usr/apps/mib2_ioc_flash $REBOOT 2>>$LOG
+		fi
+		return 2> /dev/null
 	};;
 
 	# help or unknown parameter ------------------------------
@@ -71,8 +71,8 @@ return 2> /dev/null
 		echo "Usage: "$thisname" [OPTION]"
 		echo ""
 		echo "Options:"
-		echo "        -t <sec> <fast>	reboot Unit"
-		echo "        --help			show this help"
+		echo "        -t <sec> <fast> reboot Unit"
+		echo "        --help          show this help"
 		echo ""
 		echo "This program is free software; you can redistribute it and/or"
 		echo "modify it under the terms of the GNU General Public License"
@@ -90,8 +90,6 @@ return 2> /dev/null
 		echo ""
 		
 	};;
-
-	esac
-
+esac
 exit 0
 
diff --git a/apps/setreg b/apps/setreg
--- a/apps/setreg
+++ b/apps/setreg
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-revision="setregeu v0.1.1 (2021-09-17 by MIB-Wiki)"
+revision="setregeu v0.1.5 (2023-06-12 by MIB-Wiki)"
 # use --help for more info
 
 export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
@@ -12,185 +12,137 @@ thisdir="$(dirname $0)"
 
 if [ -z $LOG ]; then
 	. $thisdir/../config/GLOBALS
-	echo -ne "\n$ME-$thisname---->\n" 2>> $LOG
 fi
+echo -ne "$ME-$thisname---->\n" | $TEE -i -a $LOG
 
 if [ -f $TMP/reboot.mib ]; then
-	echo "Reboot running..."
+	echo -ne "Aborted because the reboot is running...\n" | $TEE -a $LOG
 	return 2> /dev/null
 fi
 
-	case $1 in
+MIBCAP=3
+. $thisdir/../config/MIBCHECK
 
+if [ "$2" = "-noboot" ]; then
+	noboot=$2
+else
+	noboot=""
+fi
+
+#Get the real train not from GLOBALS but from EEPROM as it can be changed already
+TRAINVERSION="$($E2P r 3A0 19 | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )"
+
+case $1 in
 	-eu) {
+		trap '' 2
+		mount -uw /net/rcc/mnt/efs-persist
+		if [[ "$TRAINVERSION" = *ER* || "$TRAINVERSION" = *EU* ]]; then
+			echo -ne "Writing EU language datasets to 5F...\n" | $TEE -a $LOG
+			/net/mmx/fs/sda0/apps/setlang -eu -noboot
+			echo -ne "\nChanging coding and adaptations to EU:" | $TEE -a $LOG
+			echo -ne "\n--- Summer time algo\n" | $TEE -a $LOG
+			# 0=none, 1=manual, 2=MESZ, 3=USA
+			$PERSW -f -t int 28442848 503 2
+			
+			echo -ne "--- FM Band setting\n" | $TEE -a $LOG
+			# 0=BAND_FM_NO_SETTING, 1=BAND_FM_EU_RDW, 2=BAND_FM_NAR, 3=BAND_FM_JP, 4=BAND_FM_KOR
+			$PERSW -f -t int 0 1343759375 1
+			
+			echo -ne "--- AM Band setting\n" | $TEE -a $LOG
+			# 0=BAND_AM_NO_SETTING, 1=BAND_AM_EU_RDW, 2=BAND_AM_NAR, 3=BAND_AM_JP, 4=BAND_AM_EU, 5=BAND_AM_AUS
+			$PERSW -f -t int 0 1343759600 1
+			
+			#echo -ne "--- DAB Bandsetting 1\n"
+			# 0=BAND_DAB1_OFF, 1=BAND_DAB1_EU_BAND_III-N, 2=BAND_DAB1_EU_BAND_III (EU default), 3=BAND_DAB1_CANADA_L_BAND
+			# 4=BAND_DAB1_KOREA_BAND_III, 5=BAND_DAB1_CHINA_BAND_III, 6=BAND_DAB1_DOWNLOAD_TABLE_1, 7=BAND_DAB1_NEW_ZEALAND_BAND_III
+			#$PC i:0:0x5018280F 0
 
-trap '' 2
+			#echo -ne "--- DAB Bandsetting 2\n"
+			# 0=BAND_DAB2_OFF, 1=BAND_DAB2_L_BAND (EU default), 2=BAND_DAB2_DOWNLOAD_TABLE_2
+			#$PC i:0:0x501828F0 0
 
-echo -ne "1-Click EU Coding\n"
-mount -uw /net/rcc/mnt/efs-persist
-	if [[ "$TRAINVERSION" = *ER* ]]; then
-		echo -ne "EU train found\n" | $TEE -a $LOG
-		#echo -ne "NOTE: This will disable DAB functions\n"
-		#echo -ne "Converted units do not have DAB...\n"
-		echo -ne "--------\n"
-		sleep 3
-		echo -ne "visible_MMI_language_dataset - 0x2d00 - EU\n"
-		on -f mmx $PC b:10:0xC0030006 1B64655F444503656E5F47420366725F46520169745F49540165735F45530163735F435A016E6C5F4E4C0170745F50540172755F52550173765F53450174725F545202706C5F504C016E6F5F4E4F0164615F444B01656C5F47520168725F48520168755F48550166695F46490162735F424101726F5F524F01736B5F534B01736C5F53490173725F52530162675F4247016C745F4C54016C765F4C5601756B5F554101656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201656E5F474201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000304214B7
-		sleep 1
-		echo -ne "language dataset - 0x280 - GB_en\n"
-		on -f mmx $PC b:10:0xC0030005 656E5F474200656E5F474200656E5F4742004331E45D
-		sleep 1
-		echo -ne "summertime algo.\n"
-		on -f mmx $PC i:28442848:503 2
-					#  "none" 0
-					#  "manual" 1
-					#  "MESZ" 2
-					#  "USA" 3
-					sleep 1
-		echo -ne "FM Bandsetting\n"
-		on -f mmx $PC i:0:0x5018240F 1
-					# 0:		BAND_FM_NO_SETTING
-					# 1:		BAND_FM_EU_RDW
-					# 2:		BAND_FM_NAR
-					# 3:		BAND_FM_JP
-					# 4:		BAND_FM_KOR
-					sleep 1
-		echo -ne "AM Bandsetting\n"
-		on -f mmx $PC i:0:0x501824F0 1
-					# 0:		BAND_AM_NO_SETTING
-					# 1:		BAND_AM_EU_RDW
-					# 2:		BAND_AM_NAR
-					# 3:		BAND_AM_JP
-					# 4:		BAND_AM_EU
-					# 5:		BAND_AM_AUS	
-					sleep 1			
-		#echo -ne "DAB Bandsetting 1\n"
-		#on -f mmx $PC i:0:0x5018280F 0
-					# 0:		BAND_DAB1_OFF
-					# 1:		BAND_DAB1_EU_BAND_III-N
-					# 2:		BAND_DAB1_EU_BAND_III (EU default)
-					# 3:		BAND_DAB1_CANADA_L_BAND
-					# 4:		BAND_DAB1_KOREA_BAND_III
-					# 5:		BAND_DAB1_CHINA_BAND_III
-					# 6:		BAND_DAB1_DOWNLOAD_TABLE_1
-					# 7:		BAND_DAB1_NEW_ZEALAND_BAND_III
-					sleep 1			
-		#echo -ne "DAB Bandsetting 2\n"
-		#on -f mmx $PC i:0:0x501828F0 0
-					# 0:		BAND_DAB2_OFF
-					# 1:		BAND_DAB2_L_BAND (EU default)
-					# 2:		BAND_DAB2_DOWNLOAD_TABLE_2
-					sleep 1
-		echo -ne "Radiotext+ off/on\n"
-		on -f mmx $PC i:0:0x50183408 1
-		sleep 1
-		echo -ne "Navigation Country\n"
-		on -f mmx $PC i:0:0x50180CFF 1
-					#  "EU" 1
-					#  "NAR" 2
-					#  "MSA" 3
-					#  "Korea" 4
-					#  "China" 5
-					#  "Japan" 6
-					#  "AsiaPacific" 7
-					#  "Australia" 8
-					#  "South Africa" 9
-					#  "NEAST" 10
-					#  "NMAfrica" 11
-					#  "MEAST" 12
-					#  "CentralAsia" 13
-					#  "India" 14
-					#  "Israel" 15
-					#  "Taiwan" 16
-					#  "MSA 2 (Chile)" 17
-				sleep 1
-		echo -ne "Import media\n"
-		on -f mmx $PC i:0:0x50186010 1
-		sleep 1
-		echo -ne "Media Ripping\n"
-		on -f mmx $PC i:0:0x50186020 1
-		sleep 1
-		echo -ne "Regionalcodes DVD\n"
-		on -f mmx $PC i:28442848:515 2
-		sleep 1
-		echo -ne "Regionalcodes Blueray\n"
-		on -f mmx $PC i:28442848:516 2
-		sleep 1
-		echo -ne "R. Codes DVD Counter\n"
-		on -f mmx $PC i:28442848:517 5
-		sleep 1
-		echo -ne "R. Codes Blueray Counter\n"
-		on -f mmx $PC i:28442848:518 5
-		sleep 1
-		echo -ne "TMCPro EU\n"
-		on -f mmx $PC i:28442848:520 32783
-		sleep 1
-		echo -ne "Gracenote local ON\n"
-		on -f mmx $PC b:0:3221356628:1.6 1
-		on -f mmx $PC b:0:3221356628:1.7 1
-		sleep 1
-		echo -ne "Radio stationlogo DB\n"
-		on -f mmx $PC b:0:3221356628:6 1
-			#	"none" 0
-			#	"EU" 1
-			#	"Taiwan" EA
-			#	"Korea" CD
-			#	"Hongkong" 66
-			#	"China" 28
-			#	"Macao" 67
-			sleep 1
-		echo -ne "SDS region Flag\n"
-		on -f mmx $PC b:0:3221356628:9 1
-			#	"no region" 0
-			#	"EU" 1
-			#	"NAR" 2
-			#	"MSA" 3
-			#	"Korea" 4
-			#	"China" 5
-			#	"Japan" 6
-			#	"AsiaPacific" 7
-			#	"Australia" 8
-			#	"South Africa" 9
-			#	"NEAST" 10
-			#	"NMAfrica" 11
-			#	"MEAST" 12
-			#	"CentralAsia" 13
-			#	"India" 14
-			#	"Israel" 15
-			#	"Taiwan" 16
-			#	"MSA 2 (Chile)" 17
-			#	"China 2" 18
-			#	"China 3" 19
-			sleep 1
-		echo -ne "variant region\n"
-		on -f mmx $PC i:0x286f058c:9 2
-			#   "Europe/ROW" 1
-			#   "Europe" 2  
-			#   "NAR" 3
-			#   "ROW" 4 
-			#   "China" 5
-			#   "Japan" 6   
-			#   "Korea" 7
-			#   "Asia" 8
-			#   "Taiwan" 9
-			sleep 1
-		#echo -ne "switch variant feature byte type to High\n"
-		#on -f mmx $PC i:0x286f058c:4 1
-		#	sleep 1
-		echo -ne "disable variant feature byte sirius\n"
-		on -f mmx $PC i:0x286f058c:8 0
-			sleep 1
-		echo -ne "store changes to persistence\n"
-		on -f mmx $PC b:0:1 0
-			sleep 2
-		echo -ne "\nAll done! now you can go back...\n"
-	else
-		echo -ne "no EU train found - will stop here\n" | $TEE -a $LOG
-	fi
-	
-return 2> /dev/null
+			echo -ne "--- RDS switch off\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343763457 0 2>> $LOG
+
+			echo -ne "--- AF functionality on\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343763458 1 2>> $LOG
+			
+			echo -ne "--- Radiotext+ on\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343763464 1 2>> $LOG
+
+			echo -ne "--- PI Ignore off\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343763472 0 2>> $LOG
+
+			echo -ne "--- AM disable on\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343764482 1 2>> $LOG
+
+			echo -ne "--- RDS deactivation off\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343764496 0 2>> $LOG
+
+			echo -ne "--- AF deactivation off\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343764512 0 2>> $LOG
+
+			echo -ne "--- Navigation Country\n" | $TEE -a $LOG
+			# 1=EU, 2=NAR, 3=MSA, 4=Korea, 5=China, 6=Japan, 7=AsiaPacific, 8=Australia, 9=South Africa, 10=NEAST,
+			# 11=NMAfrica, 12=MEAST, 13=CentralAsia, 14=India, 15=Israel, 16=Taiwan, 17=MSA 2 (Chile)
+			$PERSW -f -t int 0 1343753471 1 2>> $LOG
+
+			echo -ne "--- Import media\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343774736 1 2>> $LOG
+
+			echo -ne "--- Media Ripping\n" | $TEE -a $LOG
+			$PERSW -f -t int 0 1343774752 1 2>> $LOG
+
+			echo -ne "--- Regional Codes DVD\n" | $TEE -a $LOG
+			$PERSW -f -t int 28442848 515 2 2>> $LOG
+
+			echo -ne "--- Regional Codes Blueray\n" | $TEE -a $LOG
+			$PERSW -f -t int 28442848 516 2 2>> $LOG
+
+			echo -ne "--- Regional Codes DVD Counter\n" | $TEE -a $LOG
+			$PERSW -f -t int 28442848 517 5 2>> $LOG
+
+			echo -ne "--- Regional Codes Blueray Counter\n" | $TEE -a $LOG
+			$PERSW -f -t int 28442848 518 5 2>> $LOG
+			
+			echo -ne "--- TMCPro EU\n" | $TEE -a $LOG
+			$PERSW -f -t int 28442848 520 32783 2>> $LOG
+
+			echo -ne "--- Gracenote local ON\n" | $TEE -a $LOG
+			$PERSW -f -P -L 1 -O 9 0 3221356628 F 2>> $LOG
+			$PERSW -f -P -L 1 -O 8 0 3221356628 F 2>> $LOG
+
+			echo -ne "--- Radio stationlogo DB\n" | $TEE -a $LOG
+			#	0=none, 1=EU, 28=China, 66=Hongkong, Macao=67, CD=Korea, EA=Taiwan
+			$PERSW -f -P -L 8 -O 48 0 3221356628 01 2>> $LOG
+			
+			echo -ne "--- SDS region Flag\n" | $TEE -a $LOG
+			# 0=no region, 1=EU, 2=NAR, 3=MSA, 4=Korea, 5=China, 6=Japan, 7=AsiaPacific, 8=Australia, 9=South Africa, 10=NEAST,
+			# 11=NMAfrica, 12=MEAST, 13=CentralAsia, 14=India, 15=Israel, 16=Taiwan, 17=MSA 2 (Chile), 18=China 2, 19=China 3
+			$PERSW -f -P -L 8 -O 72 0 3221356628 01 2>> $LOG
+
+			echo -ne "--- Variant region\n" | $TEE -a $LOG
+			# 1=Europe/ROW, 2=Europe, 3=NAR, 4=ROW, 5=China, 6=Japan, 7=Korea, 8=Asia, 9=Taiwan
+			$PERSW -f -t int 678364556 9 2 2>> $LOG
+
+			#echo -ne "switch variant feature byte type to High\n"
+			#$PC i:678364556:4 1
+
+			echo -ne "--- Disable variant feature byte sirius\n"
+			$PERSW -f -t int 678364556 8 0 2>> $LOG
+			CODING="$($E2P r F1 19 | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p'  | $SED -e 's/0x//g' | $SED -e ':a;N;$!ba;s/\n//g')"
+			echo "5F Long Coding: $CODING" >> $LOG
+
+			echo -ne "\n$thisname done!\n" | $TEE -i -a $LOG
+		else
+			echo -ne "Skipped as unit has non EU train.\n" | $TEE -a $LOG
+			exit 1
+		fi
 
 trap 2
+[ -z "$noboot" ] && . $thisdir/reboot -t 10
+[ -z "$noboot" ] && return 2> /dev/null
+
 	};;
 
 	# help or unknown parameter ------------------------------
@@ -198,11 +150,11 @@ trap 2
 		echo ""
 		echo $revision
 		echo ""
-		echo "Usage: "$thisname" [OPTION]"
+		echo "Usage: "$thisname" [OPTION] [-noboot]"
 		echo ""
 		echo "Options:"
-		echo "        -eu			set Region to EU"
-		echo "        --help		show this help"
+		echo "        -eu           set Region to EU"
+		echo "        --help        show this help"
 		echo ""
 		echo "Note: Backup will only work in RCC bash!"
 		echo ""
@@ -220,9 +172,7 @@ trap 2
 		echo "along with this program; if not, write to the Free Software Foundation,"
 		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
 		echo ""
-
 	};;
-
-	esac
+esac
 
 exit 0
diff --git a/apps/setvariant b/apps/setvariant
--- a/apps/setvariant
+++ b/apps/setvariant
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-revision="setvariant v0.1.0 (2021-12-10 by MIB-Wiki)"
+revision="setvariant v0.2.1 (2023-06-29 by MIB-Wiki)"
 # use --help for more info
 
 export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
@@ -12,44 +12,56 @@ thisdir="$(dirname $0)"
 
 if [ -z $LOG ]; then
 	. $thisdir/../config/GLOBALS
-	echo -ne "\n$ME-$thisname---->\n" 2>> $LOG
 fi
+echo -ne "$ME-$thisname---->\n" | $TEE -i -a $LOG
 
 if [ -f $TMP/reboot.mib ]; then
-	echo "Reboot running..."
+	echo -ne "Aborted because the reboot is running...\n" | $TEE -a $LOG
 	return 2> /dev/null
 fi
 
-	case $1 in
+MIBCAP=3
+. $thisdir/../config/MIBCHECK
 
-	-var) {
+if [ "$2" = "-noboot" ]; then
+	noboot=$2
+else
+	noboot=""
+fi
 
-trap '' 2
+readvar ()
+{
+echo -ne "Reading Variant_2 from EEPROM...\n" | $TEE -i -a $LOG
+echo -ne "Reading Unit Class from EEPROM...\n" | $TEE -i -a $LOG
+VARTYPE=$($E2P r DE 1 | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p') 2>> $LOG #Unit class: 01=High 04=Premium
+#echo $VARTYPE
+echo -ne "Reading Feature bits from EEPROM...\n" | $TEE -i -a $LOG
+feature_byte=$($E2P r DF 1 | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p') 2>> $LOG
+binary_value=$(echo "ibase=16; obase=2; $feature_byte" | bc ) 2>> $LOG
+binary_value=$(echo "00000000"${binary_value} | tail -c9) 2>> $LOG
+#echo $binary_value
+#feature bits
+	VARTEL="$(echo -ne $binary_value | cut -c8)" #Telephone
+	VARNAV="$(echo -ne $binary_value | cut -c7)" #Navigation
+	VARDAB="$(echo -ne $binary_value | cut -c6)" #DAB
+	VARSIR="$(echo -ne $binary_value | cut -c5)" #Sirius
+	VARLTE="$(echo -ne $binary_value | cut -c4)" #LTE
+	VAR2DNAV="$(echo -ne $binary_value | cut -c3)" #2d Nav
+	VARMMIRADIO="$(echo -ne $binary_value | cut -c2)" #MMI Radio
+	#echo 0$VARMMIRADIO$VAR2DNAV$VARLTE$VARSIR$VARDAB$VARNAV$VARTEL
+echo -ne "Reading Region from EEPROM...\n" | $TEE -i -a $LOG
+VARREG=$($E2P r E0 1 | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p') 2>> $LOG #Region: 02=EU
+#echo $VARREG
 
-echo -ne "Variant_1 will be generated from Variant_2 coding on unit\n"
-echo -ne "Variant Information can be changed in GEM\n\n"
-echo -ne "Result will be written to eeprom\n\n"
-
-#Type
-VARTYPE="$(on -f mmx $PC i:0x286f058c:4)"
-#Telephone 0/1
-#VARTEL="$(on -f mmx $PC i:0x286f058c:5)"
-#Navigation EU
-VARNAV="$(on -f mmx $PC i:0x286f058c:6)"
-#DAB 0/1
-VARDAB="$(on -f mmx $PC i:0x286f058c:7)"
-#sirius 0/1
-VARSIR="$(on -f mmx $PC i:0x286f058c:8)"
-# LTE 0/1
-VARLTE="$(on -f mmx $PC i:0x286f058c:17)"
-# region EU
-VARREG="$(on -f mmx $PC i:0x286f058c:9)"
 #error handler for variant_1
 VARERROR=0
+}
 
-if [ $VARTYPE = 1 ]; then #High
+convertvar2hex ()
+{
+if [ $VARTYPE = 01 ]; then #High
 	VARTYPE="48 "
-elif [ $VARTYPE = 4 ]; then #Premium
+elif [ $VARTYPE = 04 ]; then #Premium
 	VARTYPE="50 "
 else
 	echo -ne "Type unknown\n" | $TEE -i -a $LOG
@@ -57,9 +69,9 @@ else
 	VARERROR=1
 fi
 
-#if [ $VARTEL = 1 ]; then #ENABLED
+#if [ $VARTEL = 01 ]; then #ENABLED
 #	VARTEL="54 "
-#elif [ $VARTEL = 0 ]; then #OFF
+#elif [ $VARTEL = 00 ]; then #OFF
 #	VARTEL=""
 #else
 #	echo -ne "Telephone status unknown\n" | $TEE -i -a $LOG
@@ -107,66 +119,195 @@ else
 	VARERROR=1
 fi
 
-	case $VARREG in
-	1) VARREG="45 52 " ;; #ER
-	2) VARREG="45 55 " ;; #EU
-	3) VARREG="55 53 " ;; #US
-	4) VARREG="52 57 " ;; #RW
-	5) VARREG="43 4e " ;; #CN
-	6) VARREG="4a 50 " ;; #JP
-	7) VARREG="4B 52 " ;; #KR
-	8) VARREG=""		  #Asia?
+case $VARREG in
+	01*) VARREG="45 52 " ;; #ER
+	02*) VARREG="45 55 " ;; #EU
+	03*) VARREG="55 53 " ;; #US
+	04*) VARREG="52 57 " ;; #RW
+	05*) VARREG="43 4e " ;; #CN
+	06*) VARREG="4a 50 " ;; #JP
+	07*) VARREG="4B 52 " ;; #KR
+	08*) VARREG=""		  #Asia?
 		echo -ne "Region code 8 unknown\n" | $TEE -i -a $LOG
 		VARERROR=1 ;;
-	9) VARREG="54 57 " ;; #TW
+	09*) VARREG="54 57 " ;; #TW
 	*) VARREG=""
 		echo -ne "Region unknown\n" | $TEE -i -a $LOG
 		VARERROR=1 ;;
-		esac
+esac
+}
 
-#build variant 1 string
-#TNDL in Variant_2 is LND in Variant_1 - no T and order is different
-EVAR="4d 55 2d "$VARTYPE"2d "$VARLTE$VARNAV$VARDAB$VARSIR"2d "$VARREG
+IdentBlock ()
+{
 
-#echo $EVAR
+#find IdentBlock for unit
+
+if [[ "$TRAINVERSION" = *VW* ]] || [[ "$TRAINVERSION" = *SK* ]]; then
+	if [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 1 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav_DAB
+		IDENT="30 32 30" #020
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 1 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav_DAB_Phone
+		IDENT="30 32 31" #021
+	elif [[ "$VARLTE" = 1 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 1 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav_DAB_PhoneLTE
+		IDENT="30 32 31" #021
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 1 ]] && [[ "$VARREG" = 3 ]]; then
+		#High2_NAR_EX_Nav_Sirius
+		IDENT="30 32 36" #026
+	elif [[ "$VARLTE" = 1 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav_PhoneLTE
+		IDENT="30 34 32" #042
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav
+		IDENT="30 34 33" #043
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav_Phone
+		IDENT="30 34 34" #044
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 4 ]]; then
+		#High2_RoW_Nav
+		IDENT="30 34 35" #045
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 4 ]]; then
+		#High2_RoW_Nav_Phone
+		IDENT="30 34 36" #046
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 1 ]] && [[ "$VARREG" = 3 ]]; then
+		#High2_NAR_Nav_Sirius
+		IDENT="30 34 37" #047
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 5 ]]; then
+		#High2_CN_Nav
+		IDENT="30 34 38" #048
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 6 ]]; then
+		#High2_JP_Nav
+		IDENT="30 35 30" #050
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 8 ]]; then
+		#High2_TW_Nav
+		IDENT="30 33 32" #032
+	else
+		echo -ne "no matching IdentBlock found for this variant\n"
+	fi
+elif [[ "$TRAINVERSION" = *SE* ]]; then
+	IDENT="30 32 30" #020
+#elif [[ "$TRAINVERSION" = *AU* ]]; then
+	#TODO: Add Audi, Bentley
+elif [[ "$TRAINVERSION" = *POG* ]]; then
+	if [[ "$VARLTE" = 1 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 1 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav_DAB_PhoneLTE
+		IDENT="30 33 35" #035
+	elif [[ "$VARLTE" = 1 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav_PhoneLTE
+		IDENT="30 33 36" #036
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 1 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav_DAB
+		IDENT="30 33 37" #037
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 2 ]]; then
+		#High2_EU_Nav
+		IDENT="30 33 37" #038
+	elif [[ "$VARLTE" = 1 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 1 ]] && [[ "$VARREG" = 3 ]]; then
+		#High2_US_Nav_PhoneLTE_Sirius
+		IDENT="38 38 30" #880
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 1 ]] && [[ "$VARREG" = 3 ]]; then
+		#High2_US_Nav_Sirius
+		IDENT="38 39 31" #891
+	elif [[ "$VARLTE" = 1 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 5 ]]; then
+		#High2_CN_Nav_PhoneLTE
+		IDENT="38 39 34" #894
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 5 ]]; then
+		#High2_CN_Nav
+		IDENT="38 39 35" #895
+	elif [[ "$VARLTE" = 0 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 0 ]] && [[ "$VARSIR" = 0 ]] && [[ "$VARREG" = 7 ]]; then
+		#High2_KR_Nav
+		IDENT="38 39 39" #899
+	else
+		echo -ne "no matching IdentBlock found for this variant\n"
+	fi
+elif [[ "$TRAINVERSION" = *BY* ]]; then
+	if [[ "$VARLTE" = 1 ]] && [[ "$VARNAV" = 1 ]] && [[ "$VARDAB" = 0 ]] && [[ "$VARTEL" = 1 ]] && [[ "$VARSIR" = 1 ]] && [[ "$VARREG" = 3 ]]; then
+		#High2_US_Nav_PhoneLTE_Sirius
+		IDENT="38 39 30" #890
+	else
+		echo -ne "no matching IdentBlock found for this variant\n"
+	fi
+else
+	echo -ne "no matching IdentBlock found for this variant\n"
+fi
+
+}
+
+case $1 in
+-var) {
+trap '' 2
+
+echo -ne "---- Read original Variant_1 from unit\n" | $TEE -i -a $LOG
+COMPONENT="$($E2P r BA D | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )" 2>> $LOG
+echo -ne "---- Variant_1: $COMPONENT\n" | $TEE -i -a $LOG
+echo -ne "---- Read original Variant_2 from unit\n" | $TEE -i -a $LOG
+VARIANT2="$($SED -n 's/Variant = '\''\(.*\)'\''/\1/p' /net/rcc/dev/shmem/version.txt | $SED 's/[^a-zA-Z0-9._-]//g')" 2>> $LOG
+echo -ne "---- Variant_2: $VARIANT2\n" | $TEE -i -a $LOG
+
+readvar
+convertvar2hex
+
 
 if [ $VARERROR = 0 ]; then
-	echo -ne "---- Read original Variant_1 from unit\n" >> $LOG
-	on -f rcc /usr/apps/modifyE2P r ba 0d >> $LOG
-	echo -ne "---- Clean Variant - 13 bytes 00\n" >> $LOG
-	on -f rcc /usr/apps/modifyE2P w ba 00 00 00 00 00 00 00 00 00 00 00 00 00 >> $LOG
-	echo -ne "---- Write Variant_1\n" | $TEE -i -a $LOG
-	on -f rcc /usr/apps/modifyE2P w ba $EVAR  | $TEE -i -a $LOG
-	echo -ne "---- Read Variant_1 back for log\n" >> $LOG
-	on -f rcc /usr/apps/modifyE2P r ba 0d >> $LOG
-	#EVAR=$(echo "$EVAR" | $SED -r 's/[[:space:]]//g')
-	#AVAR=$(on -f mmx $VOLUME/apps/hex2ascii -convert $EVAR)
+	echo -ne "---- Clean Variant_1 - 13 bytes 0x20\n" | $TEE -i -a $LOG
+	$E2P w BA 20 20 20 20 20 20 20 20 20 20 20 20 20 >> $LOG
+	#Build variant 1 string
+	#TNDL in Variant_2 is LND in Variant_1 - no T and order is different
+	EVAR="4d 55 2d "$VARTYPE"2d "$VARLTE$VARNAV$VARDAB$VARSIR"2d "$VARREG
 	AVAR=$(echo "$EVAR" | $XXD -r -p)
-	echo -ne "\nNew Variant_1: "$AVAR"\n"	
-	echo -ne "\nReboot unit to apply changes\n"
+	echo -ne "---- New Variant_1: "$AVAR"\n" | $TEE -i -a $LOG
+	echo -ne "---- Writing generated Variant_1 into EEPROM\n" | $TEE -i -a $LOG
+	$E2P w BA $EVAR >> $LOG
+	COMPONENT="$($E2P r BA D | $SED -rn 's/^0x\S+\W+(.*?)$/\1/p' | $SED -rn 's:\W*(\S\S)\W*:0x\1\n:pg' | $SED -rn '/^0x/p' | $XXD -r -p | $SED 's/[^a-zA-Z0-9_-]//g' )" 2>> $LOG
+	echo -ne "New Variant_1 in EEPROM: $COMPONENT\n" | $TEE -i -a $LOG
 else
 	echo -ne "Error occured during creation of Variant_1\n" | $TEE -i -a $LOG
 	echo -ne "Check messages above\n"
 	echo -ne "No changes to Variant_1 will be applied\n\n" | $TEE -i -a $LOG
+	exit 1
 fi
+echo -ne "\n$thisname done!\n" | $TEE -i -a $LOG
 
+trap 2
+[ -z "$noboot" ] && . $thisdir/reboot -t 10
+[ -z "$noboot" ] && return 2> /dev/null
 
+};;
+
+-identblock) {
+
+trap '' 2
+
+echo -ne "IdentBlock will be derived from Variant\n" | $TEE -i -a $LOG
+
+readvar
+IdentBlock
+
+if [ ! -z $IDENT ]; then
+	echo -ne "write IdentBlock $IDENT to eeprom\n" | $TEE -i -a $LOG
+	$E2P w 86 $IDENT | $TEE -i -a $LOG
+	$E2P w 91 $IDENT | $TEE -i -a $LOG
+else
+	echo -ne "IdentBlock not found\n" | $TEE -i -a $LOG
+fi
 
 trap 2
 
-return 2> /dev/null
+[ -z "$noboot" ] && . $thisdir/reboot -t 10
+[ -z "$noboot" ] && return 2> /dev/null
 
-	};;
+};;
 
 	# help or unknown parameter ------------------------------
 	*) {
 		echo ""
 		echo $revision
 		echo ""
-		echo "Usage: "$thisname" [OPTION]"
+		echo "Usage: "$thisname" [OPTION] [-noboot]"
 		echo ""
 		echo "Options:"
 		echo "        -var			set variant_1"
+		echo "        -identblock		set IdentBlock based on variant_2"
 		echo "        --help			show this help"
 		echo ""
 		echo "Note: Backup will only work in RCC bash!"
@@ -185,9 +326,7 @@ return 2> /dev/null
 		echo "along with this program; if not, write to the Free Software Foundation,"
 		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
 		echo ""
-
 	};;
-
-	esac
+esac
 
 exit 0
